// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"EventCatalog/external"
	"EventCatalog/handler"
	"EventCatalog/repository"
)

// Injectors from wire.go:

func DependencyProvider() (*handler.EventCatalog, error) {
	host, err := external.HostProvider()
	if err != nil {
		return nil, err
	}
	databaseImpl, err := repository.DatabaseImlProvider(host)
	if err != nil {
		return nil, err
	}
	eventCatalog, err := handler.NewEventCatalog(databaseImpl)
	if err != nil {
		return nil, err
	}
	return eventCatalog, nil
}
